package Student_database;

import javax.swing.ButtonGroup;

public class second_window_netbeans extends javax.swing.JPanel {

    public second_window_netbeans() {
        initComponents();
        
        ButtonGroup personStuButton = new ButtonGroup();
        personStuButton.add(person_radio_button);
        personStuButton.add(student_radio_button);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        person_radio_button = new javax.swing.JRadioButton();
        student_radio_button = new javax.swing.JRadioButton();
        id_text_field = new javax.swing.JTextField();
        name_text_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        road_text_field = new javax.swing.JTextField();
        postoffice_text_field = new javax.swing.JTextField();
        district_text_field = new javax.swing.JTextField();
        first_item_button = new javax.swing.JButton();
        prev_item_button = new javax.swing.JButton();
        next_item_button = new javax.swing.JButton();
        last_item_button = new javax.swing.JButton();
        position_view_text_field = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        sort_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Data Manipulation Form");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Person or Student: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Name: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Address: ");

        person_radio_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        person_radio_button.setText("Person");
        person_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person_radio_buttonActionPerformed(evt);
            }
        });

        student_radio_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        student_radio_button.setText("Student");
        student_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_radio_buttonActionPerformed(evt);
            }
        });

        id_text_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id_text_field.setText("form_id_jTextField1");

        name_text_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name_text_field.setText("form_name_jTextField2");
        name_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_text_fieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Road:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("PostOffice:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("District: ");

        road_text_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        road_text_field.setText("form_road_jTextField3");
        road_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                road_text_fieldActionPerformed(evt);
            }
        });

        postoffice_text_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        postoffice_text_field.setText("form_postoffice_jTextField4");

        district_text_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        district_text_field.setText("form_district_jTextField5");

        first_item_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        first_item_button.setText("|<");
        first_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_item_buttonActionPerformed(evt);
            }
        });

        prev_item_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        prev_item_button.setText("<");

        next_item_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        next_item_button.setText(">");
        next_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_item_buttonActionPerformed(evt);
            }
        });

        last_item_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        last_item_button.setText(">|");

        position_view_text_field.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        position_view_text_field.setText("jTextField1");

        add_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        add_button.setText("Add");

        delete_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        delete_button.setText("Delete");

        sort_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        sort_button.setText("Sort");

        update_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        update_button.setText("Update");

        close_button.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        close_button.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(id_text_field, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(person_radio_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(student_radio_button)))
                                        .addGap(211, 211, 211))
                                    .addComponent(name_text_field, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(road_text_field)
                                            .addComponent(postoffice_text_field)
                                            .addComponent(district_text_field)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(first_item_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(prev_item_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(position_view_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(next_item_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(last_item_button))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(add_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(delete_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sort_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(update_button)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(close_button)))))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(person_radio_button)
                    .addComponent(student_radio_button))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(road_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(postoffice_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(district_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_item_button)
                    .addComponent(prev_item_button)
                    .addComponent(next_item_button)
                    .addComponent(last_item_button)
                    .addComponent(position_view_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button)
                    .addComponent(delete_button)
                    .addComponent(sort_button)
                    .addComponent(update_button)
                    .addComponent(close_button))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void road_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_road_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_road_text_fieldActionPerformed

    private void person_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person_radio_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person_radio_buttonActionPerformed

    private void student_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_radio_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_radio_buttonActionPerformed

    private void name_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_text_fieldActionPerformed

    private void first_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_item_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_item_buttonActionPerformed

    private void next_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_item_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_next_item_buttonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton close_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField district_text_field;
    private javax.swing.JButton first_item_button;
    private javax.swing.JTextField id_text_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton last_item_button;
    private javax.swing.JTextField name_text_field;
    private javax.swing.JButton next_item_button;
    private javax.swing.JRadioButton person_radio_button;
    private javax.swing.JTextField position_view_text_field;
    private javax.swing.JTextField postoffice_text_field;
    private javax.swing.JButton prev_item_button;
    private javax.swing.JTextField road_text_field;
    private javax.swing.JButton sort_button;
    private javax.swing.JRadioButton student_radio_button;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables



}
